-- Schéma initial PostgreSQL — portage fidèle du schéma SQLite (backend/data/comptabilite.db).
-- Idempotent : rejouable sans risque (IF NOT EXISTS partout).
--
-- Choix de portage :
--  * Les dates métier (date_emission, date_depense, ...) et les horodatages
--    (created_at, updated_at) restent en TEXT aux formats 'YYYY-MM-DD' et
--    'YYYY-MM-DD HH24:MI:SS' (UTC) pour un comportement identique à SQLite côté API.
--  * INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--    (BY DEFAULT pour autoriser l'import des ids existants lors de la migration de données).
--  * Le CHECK sur clients.statut inclut les statuts proforma utilisés par le frontend
--    ('accepte', 'refuse', 'expire', 'converti') en plus de la liste SQLite d'origine.

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('facture', 'proforma')),
  numero TEXT UNIQUE NOT NULL,
  client TEXT NOT NULL,
  customer_id BIGINT,
  montant BIGINT NOT NULL,
  date_emission TEXT NOT NULL,
  date_relance TEXT,
  date_validite TEXT,
  statut TEXT NOT NULL DEFAULT 'brouillon'
    CHECK (statut IN ('brouillon', 'envoye', 'relance', 'acompte', 'solde', 'annule',
                      'accepte', 'refuse', 'expire', 'converti')),
  montant_acompte BIGINT DEFAULT 0,
  notes TEXT,
  pj_filename TEXT,
  pj_path TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS fournisseurs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('facture_fournisseur', 'depense')),
  numero TEXT,
  fournisseur TEXT NOT NULL,
  supplier_id BIGINT,
  categorie TEXT,
  montant BIGINT NOT NULL,
  date_depense TEXT NOT NULL,
  date_echeance TEXT,
  statut TEXT NOT NULL DEFAULT 'impayee'
    CHECK (statut IN ('impayee', 'acompte_verse', 'payee', 'annule')),
  montant_acompte BIGINT DEFAULT 0,
  notes TEXT,
  pj_filename TEXT,
  pj_path TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'entreprise' CHECK (type IN ('entreprise', 'particulier')),
  name TEXT NOT NULL,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  country TEXT DEFAULT 'Cote dIvoire',
  tax_id TEXT,
  rccm TEXT,
  default_payment_terms_days INTEGER DEFAULT 30,
  notes TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  tax_id TEXT,
  rccm TEXT,
  notes TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS document_line_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  document_type TEXT NOT NULL
    CHECK (document_type IN ('facture', 'proforma', 'facture_fournisseur', 'depense')),
  description TEXT NOT NULL,
  quantity DOUBLE PRECISION DEFAULT 1,
  unit TEXT DEFAULT 'unité',
  unit_price BIGINT NOT NULL,
  discount_type TEXT DEFAULT 'none' CHECK (discount_type IN ('none', 'percent', 'fixed')),
  discount_value DOUBLE PRECISION DEFAULT 0,
  tax_rate DOUBLE PRECISION DEFAULT 0,
  line_subtotal BIGINT NOT NULL,
  line_tax BIGINT DEFAULT 0,
  line_total BIGINT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS customer_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  payment_date TEXT NOT NULL,
  amount BIGINT NOT NULL,
  payment_method TEXT DEFAULT 'virement',
  reference TEXT,
  receiving_account TEXT,
  attachment_filename TEXT,
  attachment_path TEXT,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS supplier_disbursements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_id BIGINT NOT NULL,
  supplier_id BIGINT NOT NULL,
  payment_date TEXT NOT NULL,
  amount BIGINT NOT NULL,
  payment_method TEXT DEFAULT 'virement',
  reference TEXT,
  source_account TEXT,
  attachment_filename TEXT,
  attachment_path TEXT,
  notes TEXT,
  created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS numbering_sequences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prefix TEXT NOT NULL,
  year INTEGER NOT NULL,
  last_number INTEGER DEFAULT 0,
  UNIQUE (prefix, year)
);

CREATE INDEX IF NOT EXISTS idx_clients_customer_id ON clients (customer_id);
CREATE INDEX IF NOT EXISTS idx_fournisseurs_supplier_id ON fournisseurs (supplier_id);
CREATE INDEX IF NOT EXISTS idx_line_items_document ON document_line_items (document_id, document_type);
CREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON customer_payments (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer_id ON customer_payments (customer_id);
CREATE INDEX IF NOT EXISTS idx_disbursements_expense_id ON supplier_disbursements (expense_id);
CREATE INDEX IF NOT EXISTS idx_disbursements_supplier_id ON supplier_disbursements (supplier_id);
